application: calenderp
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /worker/.*
  script: code.py
  login: admin

- url: /refresh
  script: code.py
  login: admin

- url: /test.*
  script: gaeunit.py
  login: admin

- url: /.*
  script: code.py