application: calenderp
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /worker
  script: code.py
  login: admin

- url: /.*
  script: code.py

